services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: no

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb-data:/chroma/data
    restart: no

  rag-app:
    build: .
    volumes:
      - ./documents:/app/documents
      - ./src/:/app/src
      - ./chroma_db:/app/chroma_db
    depends_on:
      - ollama
      - chromadb
    environment:
      - OLLAMA_HOST=http://ollama:11434
    stdin_open: true
    tty: true

volumes:
  ollama-data:
  chromadb-data: